name: translate

on:
  workflow_dispatch:
  push:
    branches:
      - beta
      
jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:


      # 3️⃣ Lancement du plugin de traduction
      - name: Traduction automatique
        uses: Mips2648/plugins-translations@v5
        with:
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          include_empty_translation: true
          target_languages: "en_US,es_ES,de_DE,it_IT,pt_PT"
